defaults:
  - paths: default
  - hparams: default
  - _self_

project_name: pino_research

# hydra output directory configuration
hydra:
  run:
    dir: ${paths.output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${paths.output_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}